[build]
builder = "NIXPACKS"

[deploy]
healthcheck = "/health"

[[services]]
name = "sloganizer-backend"
source = "backend"

[services.build]
builder = "NIXPACKS"

[services.variables]
NODE_ENV = "production"
PORT = "3001"

[services.healthcheck]
path = "/health"
timeout = 30
interval = 10

[[services]]
name = "sloganizer-frontend"
source = "frontend"

[services.build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[services.variables]
NODE_ENV = "production"

[services.healthcheck]
path = "/"
timeout = 30
interval = 10